firstname = input("Enter first name: ")
lastname = input("Enter last name: ")
middlename = input("Enter middle name: ")
birthdate = input("Enter birth date (MM/DD/YYYY): ")
gender = input("Enter gender: ")
address = input("Enter address: ")
course = input("Enter course: ")
yearlevel = input("Enter year level: ")

print("\n--- Entered Information ---")
print("First Name:" ,firstname)
print("Last Name:",lastname)
print("Middle Name:",middlename)
print("Birthday:",birthdate)
print("Gender:",gender)
print("Address:",address)
print("Course:",course)
print("Year Level:",yearlevel)
print("----- END -----")